# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
from heat.engine import properties
from heat.engine import constraints
from heat.engine import attributes
from heat.common.i18n import _
from avi.heat.avi_resource import AviResource
from options import *

from options import *


class AnomalyEventDetails(object):
    # all schemas
    deviation_schema = properties.Schema(
        properties.Schema.NUMBER,
        _(""),
        required=False,
        update_allowed=True,
    )
    value_schema = properties.Schema(
        properties.Schema.NUMBER,
        _(""),
        required=True,
        update_allowed=True,
    )
    metric_timestamp_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
        update_allowed=True,
    )
    model_schema = properties.Schema(
        properties.Schema.STRING,
        _("Deprecated"),
        required=False,
        update_allowed=True,
    )
    metric_id_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
        update_allowed=True,
    )
    priority_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
        update_allowed=True,
    )
    node_id_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
        update_allowed=True,
    )
    obj_type_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
        update_allowed=True,
    )
    server_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
        update_allowed=True,
    )
    pool_uuid_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
        update_allowed=True,
    )
    pool_name_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
        update_allowed=True,
    )
    models_item_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
        update_allowed=False,
    )
    models_schema = properties.Schema(
        properties.Schema.LIST,
        _(""),
        schema=models_item_schema,
        required=False,
        update_allowed=True,
    )

    # properties list
    PROPERTIES = (
        'deviation',
        'value',
        'metric_timestamp',
        'model',
        'metric_id',
        'priority',
        'node_id',
        'obj_type',
        'server',
        'pool_uuid',
        'pool_name',
        'models',
    )

    # mapping of properties to their schemas
    properties_schema = {
        'deviation': deviation_schema,
        'value': value_schema,
        'metric_timestamp': metric_timestamp_schema,
        'model': model_schema,
        'metric_id': metric_id_schema,
        'priority': priority_schema,
        'node_id': node_id_schema,
        'obj_type': obj_type_schema,
        'server': server_schema,
        'pool_uuid': pool_uuid_schema,
        'pool_name': pool_name_schema,
        'models': models_schema,
    }
