# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
from heat.engine import properties
from heat.engine import constraints
from heat.engine import attributes
from heat.common.i18n import _
from avi.heat.avi_resource import AviResource
from options import *

from options import *
from cloud_objects import *
from cloud_properties import *
from syserr import *
from system import *


class CC_VnicInfo(object):
    # all schemas
    network_uuid_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
    )
    vrf_uuid_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )
    subnet_uuid_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )

    # properties list
    PROPERTIES = (
        'network_uuid',
        'vrf_uuid',
        'subnet_uuid',
    )

    # mapping of properties to their schemas
    properties_schema = {
        'network_uuid': network_uuid_schema,
        'vrf_uuid': vrf_uuid_schema,
        'subnet_uuid': subnet_uuid_schema,
    }
