# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
from heat.engine import properties
from heat.engine import constraints
from heat.engine import attributes
from heat.common.i18n import _
from avi.heat.avi_resource import AviResource
from options import *



class SeVersion(object):
    # all schemas
    name_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
    )
    version_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
    )

    # properties list
    PROPERTIES = (
        'name',
        'version',
    )

    # mapping of properties to their schemas
    properties_schema = {
        'name': name_schema,
        'version': version_schema,
    }


class ControllerVersion(object):
    # all schemas
    name_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
    )
    version_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
    )

    # properties list
    PROPERTIES = (
        'name',
        'version',
    )

    # mapping of properties to their schemas
    properties_schema = {
        'name': name_schema,
        'version': version_schema,
    }
