# GENERATED FILE - DO NOT EDIT THIS FILE UNLESS YOU ARE A WIZZARD
#pylint:  skip-file
from heat.engine import properties
from heat.engine import constraints
from heat.engine import attributes
from heat.common.i18n import _
from avi.heat.avi_resource import AviResource
from options import *

from options import *


class SeMgrEventDetails(object):
    # all schemas
    name_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
    )
    reason_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )
    host_uuid_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )
    host_name_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )
    vs_uuid_item_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
    )
    vs_uuid_schema = properties.Schema(
        properties.Schema.LIST,
        _(""),
        schema=vs_uuid_item_schema,
        required=False,
    )
    vs_name_item_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=True,
    )
    vs_name_schema = properties.Schema(
        properties.Schema.LIST,
        _(""),
        schema=vs_name_item_schema,
        required=False,
    )
    vcpus_schema = properties.Schema(
        properties.Schema.NUMBER,
        _(""),
        required=False,
    )
    memory_schema = properties.Schema(
        properties.Schema.NUMBER,
        _(""),
        required=False,
    )
    se_grp_uuid_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )
    se_grp_name_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )
    cloud_uuid_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )
    cloud_name_schema = properties.Schema(
        properties.Schema.STRING,
        _(""),
        required=False,
    )

    # properties list
    PROPERTIES = (
        'name',
        'reason',
        'host_uuid',
        'host_name',
        'vs_uuid',
        'vs_name',
        'vcpus',
        'memory',
        'se_grp_uuid',
        'se_grp_name',
        'cloud_uuid',
        'cloud_name',
    )

    # mapping of properties to their schemas
    properties_schema = {
        'name': name_schema,
        'reason': reason_schema,
        'host_uuid': host_uuid_schema,
        'host_name': host_name_schema,
        'vs_uuid': vs_uuid_schema,
        'vs_name': vs_name_schema,
        'vcpus': vcpus_schema,
        'memory': memory_schema,
        'se_grp_uuid': se_grp_uuid_schema,
        'se_grp_name': se_grp_name_schema,
        'cloud_uuid': cloud_uuid_schema,
        'cloud_name': cloud_name_schema,
    }
